spring:
  datasource:
    url: jdbc:mysql://localhost:3306/realestate_db?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
# JWT Configuration
jwt:
  secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
  access-token-expiration: 3600000 # 1 hour in milliseconds
  refresh-token-expiration: 86400000 # 24 hours in milliseconds
# Logging Configuration
logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    com.example.datn_realeaste_crm: DEBUG
# Server configuration
server:
  port: 8088
  servlet:
    context-path: /api